const quotes = [
  "The only way to do great work is to love what you do. - Steve Jobs",
  "In the middle of difficulty lies opportunity. - Albert Einstein",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
  "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Our greatest glory is not in never falling, but in rising every time we fall. - Confucius",
  "The only impossible journey is the one you never begin. - Tony Robbins",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "It always seems impossible until it's done. - Nelson Mandela",
  "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
  "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
  "Life is what happens to you while you're busy making other plans. - John Lennon",
  "The purpose of our lives is to be happy. - Dalai Lama",
  "Get busy living or get busy dying. - Stephen King",
  "You only live once, but if you do it right, once is enough. - Mae West",
  "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
  "To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde",
  "The unexamined life is not worth living. - Socrates",
  "Life is really simple, but we insist on making it complicated. - Confucius",
  "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
  "Be yourself; everyone else is already taken. - Oscar Wilde",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
  "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "Go confidently in the direction of your dreams! Live the life you've imagined. - Henry David Thoreau",
  "The secret of getting ahead is getting started. - Mark Twain",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "Don't be pushed around by the problems in your life. Be pushed by the dreams in your heart. - Unknown",
  "The mind is everything. What you think you become. - Buddha",
  "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
  "The only way to have a friend is to be one. - Ralph Waldo Emerson",
  "The best revenge is massive success. - Frank Sinatra",
  "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
  "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "Try not to become a man of success, but rather try to become a man of value. - Albert Einstein",
  "The secret of success is to do the common thing uncommonly well. - John D. Rockefeller Jr.",
  "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
  "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will. - Vince Lombardi",
  "Success is not in what you have, but who you are. - Bo Bennett",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "Success is nothing more than a few simple disciplines, practiced every day. - Jim Rohn",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
  "The greatest pleasure in life is doing what people say you cannot do. - Walter Bagehot",
  "The only person who never makes mistakes is the person who never does anything. - Theodore Roosevelt",
  "Mistakes are the portals of discovery. - James Joyce",
  "The only real mistake is the one from which we learn nothing. - Henry Ford",
  "A man who has never made a mistake has never tried anything new. - Albert Einstein",
  "The greatest mistake you can make in life is to be continually fearing you will make one. - Elbert Hubbard",
  "Failure is the condiment that gives success its flavor. - Truman Capote",
  "Every great dream begins with a dreamer. - Harriet Tubman",
  "The best way to predict your future is to create it. - Abraham Lincoln",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "Dream big and dare to fail. - Norman Vaughan",
  "All our dreams can come true if we have the courage to pursue them. - Walt Disney",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "You miss 100% of the shots you don't take. - Wayne Gretzky",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Innovation distinguishes between a leader and a follower. - Steve Jobs",
  "Stay hungry, stay foolish. - Steve Jobs",
  "Your time is limited, so don't waste it living someone else's life. - Steve Jobs",
  "Have the courage to follow your heart and intuition. - Steve Jobs",
  "The only thing more important than your goals is your time. - Unknown",
  "Time is what we want most, but what we use worst. - William Penn",
  "The bad news is time flies. The good news is you're the pilot. - Michael Altshuler",
  "Time isn't the main thing. It's the only thing. - Miles Davis",
  "The two most powerful warriors are patience and time. - Leo Tolstoy",
  "Knowledge is power. - Francis Bacon",
  "The only source of knowledge is experience. - Albert Einstein",
  "Education is the most powerful weapon which you can use to change the world. - Nelson Mandela",
  "The more that you read, the more things you will know. The more that you learn, the more places you'll go. - Dr. Seuss",
  "The beautiful thing about learning is that nobody can take it away from you. - B.B. King",
  "Change is the only constant in life. - Heraclitus",
  "Be the change you wish to see in the world. - Mahatma Gandhi",
  "Change your thoughts and you change your world. - Norman Vincent Peale",
  "It is not the strongest of the species that survive, but the one most responsive to change. - Charles Darwin",
  "The measure of intelligence is the ability to change. - Albert Einstein",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people. - Eleanor Roosevelt",
  "The greatest leader is not necessarily the one who does the greatest things. He is the one that gets the people to do the greatest things. - Ronald Reagan",
  "A leader is one who knows the way, goes the way, and shows the way. - John C. Maxwell",
  "To handle yourself, use your head; to handle others, use your heart. - Eleanor Roosevelt",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. - Steve Jobs",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
  "The key to success is to focus on goals, not obstacles. - Unknown",
  "Success comes in cans, not can'ts. - Unknown",
  "The difference between the impossible and the possible lies in a person's determination. - Tommy Lasorda",
  "Motivation gets you started. Habit keeps you going. - Jim Ryun",
  "The secret of change is to focus all of your energy not on fighting the old, but on building the new. - Socrates",
  "Life is 10% what happens to you and 90% how you react to it. - Charles R. Swindoll",
  "The only way to survive is to embrace change. - Unknown",
  "In the end, we only regret the chances we didn't take. - Unknown",
  "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
  "Everything you've ever wanted is on the other side of fear. - George Addair",
  "The best revenge is to be unlike him who performed the injury. - Marcus Aurelius",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit. - Aristotle"
];

// let iner=document.querySelector('.disk');
// let index=Math.floor(Math.random()*quotes.length);

// iner.textContent=quotes[index];


setInterval(()=>{
let iner=document.querySelector('.disk');
let index=Math.floor(Math.random()*quotes.length);

iner.textContent=quotes[index];
},1000)